<a href="https://colab.research.google.com/github/Gilbert228/KAG_PROJECT_NUMPy/blob/main/KAG_PROJECT_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reading DataSet

In [ ]:
project_data="/content/drive/MyDrive/Colab Notebooks/Data processing /KAG_Conversion_Data.csv"

# Importing Library

In [ ]:
import numpy as np
data=np.genfromtxt(project_data,delimiter=",", skip_header=1)
data_str=np.genfromtxt(project_data,delimiter=",", skip_header=1,dtype='str')
print(data)

[[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [ ]:
import pandas as pd
df = pd.read_csv(project_data)

df.head()

ad_id  xyz_campaign_id  fb_campaign_id    age gender  interest  \
0  708746              916          103916  30-34      M        15   
1  708749              916          103917  30-34      M        16   
2  708771              916          103920  30-34      M        20   
3  708815              916          103928  30-34      M        28   
4  708818              916          103928  30-34      M        28   

   Impressions  Clicks  Spent  Total_Conversion  Approved_Conversion  
0         7350       1   1.43                 2                    1  
1        17861       2   1.82                 2                    0  
2          693       0   0.00                 1                    0  
3         4259       1   1.25                 1                    0  
4         4133       1   1.29                 1                    1

In [ ]:
xyz_id=data[:,1]
unique_id = np.unique(xyz_id)

In [ ]:
unique_id

array([ 916.,  936., 1178.])

In [ ]:
len(xyz_id[xyz_id==unique_id[0]])

54

In [ ]:
len(xyz_id[xyz_id==unique_id[1]])

464

In [ ]:
len(xyz_id[xyz_id==unique_id[2]])

625

In [ ]:
age=data_str[:,3]
unique_age_group=np.unique(age)
print(unique_age_group)

['30-34' '35-39' '40-44' '45-49']


In [ ]:
spent=data[:,8]
avg_spent=np.average(spent)
print(avg_spent)
print(spent.max())
print(spent.min())

51.36065613141295
639.9499981
0.0


In [ ]:
clicks = data[:,7]
clicks

array([  1.,   2.,   0., ...,  28., 135., 114.])

In [ ]:
unique_id

array([ 916.,  936., 1178.])

In [ ]:
print("Clicks for Id 916 :",sum(clicks[xyz_id==unique_id[0]]))
print("Clicks for Id 936 :",sum(clicks[xyz_id==unique_id[1]]))
print("Clicks for Id 1178 :",sum(clicks[xyz_id==unique_id[2]]))

Clicks for Id 916 : 113.0
Clicks for Id 936 : 1984.0
Clicks for Id 1178 : 36068.0


In [ ]:
approved_conversion=data[:,10]
#sumof_ap_conversion= sum(approved_conversion[xyz])
sum(approved_conversion[approved_conversion != 0])

1079.0

In [ ]:
sum(approved_conversion[xyz_id==unique_id[2]])

872.0

In [ ]:
max_pr = max(approved_conversion)
max_pr

21.0

In [ ]:
data_str[approved_conversion==max_pr]

array([['1121104', '1178', '144533', '30-34', 'M', '16', '2080666',
        '202', '360.1500015', '40', '21']], dtype='<U11')

In [ ]:
df_prod = pd.DataFrame(data_str[approved_conversion==max_pr],columns=df.columns)
df_prod

ad_id xyz_campaign_id fb_campaign_id    age gender interest Impressions  \
0  1121104            1178         144533  30-34      M       16     2080666   

  Clicks        Spent Total_Conversion Approved_Conversion  
0    202  360.1500015               40                  21